apiVersion: v1
kind: Template
metadata:
  name: activeTemplate
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: activemq
    name: activemq
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: activemq:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /consumer
      git:
        ref: master
        uri: https://git.uscis.dhs.gov/esb-mod/active-spring-demo/
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-webserver30-tomcat8-openshift:1.2
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: aaaa13cabf489e9a
      type: Generic
    - github:
        secret: 57367f4ae7fdd3cd
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Build
  metadata:
    annotations:
    labels:
      app: activemq
      buildconfig: activemq
      openshift.io/build-config.name: activemq
      openshift.io/build.start-policy: Serial
    name: activemq-1
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: activemq:latest
    postCommit: {}
    resources: {}
    serviceAccount: builder
    source:
      contextDir: /consumer
      git:
        ref: master
        uri: https://git.uscis.dhs.gov/esb-mod/active-spring-demo/
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name:  10.103.137.89:4443/jboss-webserver-3/webserver30-tomcat8-openshift
      type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: activemq
    name: activemq
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: activemq
    name: activemq
  spec:
    replicas: 1
    selector:
      deploymentconfig: activemq
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: activemq
          deploymentconfig: activemq
      spec:
        containers:
        - image: activemq:latest
          imagePullPolicy: Always
          name: activemq
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - activemq
        from:
          kind: ImageStreamTag
          name: 10.103.137.89:4443/activemq:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: activemq
    name: activemq
  spec:
    host: activemq-active-demo.os.rezie.uk
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: activemq
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: activemq
    name: activemq
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: activemq
    sessionAffinity: None
    type: ClusterIP